# Generated by Django 5.1.15 on 2026-09-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('timetable_image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('year_of_study', models.IntegerField(default=2)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.group')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'db_table': 'professors',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('year_level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.group')),
                ('professor', models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.professor')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.subject')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='GroupTimetableSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('course_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='api.courseclass')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='api.group')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'db_table': 'group_timetable',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homework_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.CharField(max_length=100)),
                ('course_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='api.courseclass')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
                'db_table': 'homeworks',
            },
        ),
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('course_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sessions', to='api.courseclass')),
            ],
            options={
                'verbose_name': 'Lecture Session',
                'verbose_name_plural': 'Lecture Sessions',
                'db_table': 'lecture_sessions',
                'unique_together': {('course_class', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('student', models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_settings', serialize=False, to='api.student')),
                ('enabled', models.IntegerField(default=1)),
                ('minutes_before', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='ScheduleOverride',
            fields=[
                ('override_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('valid_from', models.CharField(blank=True, max_length=50, null=True)),
                ('valid_to', models.CharField(blank=True, max_length=50, null=True)),
                ('course_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_overrides', to='api.courseclass')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_overrides', to='api.student')),
            ],
            options={
                'verbose_name': 'Schedule Override',
                'verbose_name_plural': 'Schedule Overrides',
                'db_table': 'student_schedule_overrides',
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='api.lecturesession')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='api.student')),
            ],
            options={
                'verbose_name': 'Sent Notification',
                'verbose_name_plural': 'Sent Notifications',
                'db_table': 'sent_notifications',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_done', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('homework', models.ForeignKey(db_column='homework_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.homework')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='api.student')),
            ],
            options={
                'verbose_name': 'Homework Submission',
                'verbose_name_plural': 'Homework Submissions',
                'db_table': 'homework_submissions',
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='absent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('makeup_session', models.ForeignKey(blank=True, db_column='makeup_session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeups', to='api.lecturesession')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.lecturesession')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance',
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=50)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('course_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.courseclass')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'student_class_enrollment',
                'unique_together': {('student', 'course_class')},
            },
        ),
    ]
