# Generated by Django 6.1.1 on 2026-09-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sync_subject_year_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNotificationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_date', models.DateField()),
                ('slot_key', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_reminders', to='api.student')),
            ],
            options={
                'verbose_name': 'Class Notification Log',
                'verbose_name_plural': 'Class Notification Logs',
                'db_table': 'class_notification_logs',
                'unique_together': {('student', 'notification_date', 'slot_key')},
            },
        ),
    ]
