# Generated by Django 6.1.1 on 2026-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classnotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
