# Generated by Django 6.1.1 on 2026-09-06 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_is_premium_student_premium_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_amount', models.IntegerField(default=10000)),
                ('salt', models.IntegerField(db_index=True)),
                ('total_amount', models.IntegerField(db_index=True)),
                ('card_number', models.CharField(max_length=30)),
                ('card_holder', models.CharField(default='Asliddin Tursunov', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.student')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_message', models.TextField()),
                ('extracted_amount', models.IntegerField(blank=True, null=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Payment Audit Log',
                'verbose_name_plural': 'Payment Audit Logs',
                'db_table': 'payment_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'total_amount', 'expires_at'], name='payment_tra_status_b487c3_idx'),
        ),
    ]
