# Generated by Django 6.1.1 on 2026-09-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_paymenttransaction_card_holder_botuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentauditlog',
            name='extracted_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
